// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpV9dnDJaz_nTN3LfNHEm700k0AHGo_js',
    appId: '1:208805151552:web:758b628d5591fee9f1b0a5',
    messagingSenderId: '208805151552',
    projectId: 'elder-voice-assist',
    authDomain: 'elder-voice-assist.firebaseapp.com',
    storageBucket: 'elder-voice-assist.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDXDwMubkFjhLZSm7OwMqU_wUgQoIemuc',
    appId: '1:208805151552:android:b9620b5854c9068bf1b0a5',
    messagingSenderId: '208805151552',
    projectId: 'elder-voice-assist',
    storageBucket: 'elder-voice-assist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlqGbS4zpyIatqC0bo0B0MtgqDov5V77g',
    appId: '1:208805151552:ios:199e639b46bf0069f1b0a5',
    messagingSenderId: '208805151552',
    projectId: 'elder-voice-assist',
    storageBucket: 'elder-voice-assist.firebasestorage.app',
    iosBundleId: 'com.example.elderVoiceAssist',
  );
}
